<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Maxwell" ignored="0" name="用户管理系统测试用例" tests="7" failures="2" timestamp="18 九月 2019 03:16:03 GMT" time="66.806" errors="0">
  <testcase name="loginTrue" time="1.409" classname="com.course.cases.LoginTest"/>
  <testcase name="loginFalse" time="0.047" classname="com.course.cases.LoginTest"/>
  <testcase name="addUser" time="10.054" classname="com.course.cases.AddUserTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.course.cases.AddUserTest.addUser(AddUserTest.java:34)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addUser -->
  <testcase name="getUserInfo" time="0.075" classname="com.course.cases.GetUserInfoTest"/>
  <testcase name="updateUserInfo" time="25.069" classname="com.course.cases.UpdateUserInfoTest"/>
  <testcase name="deleteUser" time="30.045" classname="com.course.cases.UpdateUserInfoTest">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
	at com.course.cases.UpdateUserInfoTest.deleteUser(UpdateUserInfoTest.java:49)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
  <testcase name="getUserListInfo" time="0.051" classname="com.course.cases.GetUserInfoListTest"/>
</testsuite> <!-- 用户管理系统测试用例 -->
